package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agreement implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("AgreementId")
	private java.lang.String agreementId;

	@org.kie.api.definition.type.Label("PartyId")
	private java.lang.String partyId;

	@org.kie.api.definition.type.Label("PersonId")
	private java.lang.String personId;

	@org.kie.api.definition.type.Label("product Specification Id")
	private java.lang.String productSpecificationId;

	@org.kie.api.definition.type.Label("process Instance Id")
	private java.lang.Long processInstanceId;

	@org.kie.api.definition.type.Label("dueDate")
	private java.lang.String dueDate;

	@org.kie.api.definition.type.Label("notificationDate")
	private java.lang.String notificationDate;

	@org.kie.api.definition.type.Label("tabInformation")
	private java.util.List<java.lang.String> tabInformation;

	@org.kie.api.definition.type.Label(value = "leadDetails")
	private java.lang.String leadDetails;

	@org.kie.api.definition.type.Label(value = "quoteDetails")
	private java.lang.String quoteDetails;

	@org.kie.api.definition.type.Label(value = "userDetails")
	private java.lang.String userDetails;

	public agreement() {
	}

	public java.lang.String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(java.lang.String agreementId) {
		this.agreementId = agreementId;
	}

	public java.lang.String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(java.lang.String partyId) {
		this.partyId = partyId;
	}

	public java.lang.String getPersonId() {
		return this.personId;
	}

	public void setPersonId(java.lang.String personId) {
		this.personId = personId;
	}

	public java.lang.String getProductSpecificationId() {
		return this.productSpecificationId;
	}

	public void setProductSpecificationId(
			java.lang.String productSpecificationId) {
		this.productSpecificationId = productSpecificationId;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.lang.String dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getNotificationDate() {
		return this.notificationDate;
	}

	public void setNotificationDate(java.lang.String notificationDate) {
		this.notificationDate = notificationDate;
	}

	public java.util.List<java.lang.String> getTabInformation() {
		return this.tabInformation;
	}

	public void setTabInformation(
			java.util.List<java.lang.String> tabInformation) {
		this.tabInformation = tabInformation;
	}

	public java.lang.String getLeadDetails() {
		return this.leadDetails;
	}

	public void setLeadDetails(java.lang.String leadDetails) {
		this.leadDetails = leadDetails;
	}

	public java.lang.String getQuoteDetails() {
		return this.quoteDetails;
	}

	public void setQuoteDetails(java.lang.String quoteDetails) {
		this.quoteDetails = quoteDetails;
	}

	public java.lang.String getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(java.lang.String userDetails) {
		this.userDetails = userDetails;
	}

	public agreement(java.lang.String agreementId, java.lang.String partyId,
			java.lang.String personId, java.lang.String productSpecificationId,
			java.lang.Long processInstanceId, java.lang.String dueDate,
			java.lang.String notificationDate,
			java.util.List<java.lang.String> tabInformation,
			java.lang.String leadDetails, java.lang.String quoteDetails,
			java.lang.String userDetails) {
		this.agreementId = agreementId;
		this.partyId = partyId;
		this.personId = personId;
		this.productSpecificationId = productSpecificationId;
		this.processInstanceId = processInstanceId;
		this.dueDate = dueDate;
		this.notificationDate = notificationDate;
		this.tabInformation = tabInformation;
		this.leadDetails = leadDetails;
		this.quoteDetails = quoteDetails;
		this.userDetails = userDetails;
	}

}