package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agreementFacilitateBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("agreementId")
	private java.lang.String agreementId;
	@org.kie.api.definition.type.Label("partyId")
	private java.lang.String partyId;
	@org.kie.api.definition.type.Label("personId")
	private java.lang.String personId;
	@org.kie.api.definition.type.Label("dueDate")
	private java.lang.String dueDate;
	@org.kie.api.definition.type.Label("notificationDate")
	private java.lang.String notificationDate;
	@org.kie.api.definition.type.Label("isDocUploadedNeeded")
	private java.lang.Boolean isDocUploadedNeeded;
	@org.kie.api.definition.type.Label("isemailNeeded")
	private java.lang.Boolean isemailNeeded;
	@org.kie.api.definition.type.Label("leadDetails")
	private java.lang.String leadDetails;
	@org.kie.api.definition.type.Label(value = "processInstanceId")
	private java.lang.Long processInstanceId;

	public agreementFacilitateBO() {
	}

	public java.lang.String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(java.lang.String agreementId) {
		this.agreementId = agreementId;
	}

	public java.lang.String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(java.lang.String partyId) {
		this.partyId = partyId;
	}

	public java.lang.String getPersonId() {
		return this.personId;
	}

	public void setPersonId(java.lang.String personId) {
		this.personId = personId;
	}

	public java.lang.String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.lang.String dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getNotificationDate() {
		return this.notificationDate;
	}

	public void setNotificationDate(java.lang.String notificationDate) {
		this.notificationDate = notificationDate;
	}

	public java.lang.Boolean getIsDocUploadedNeeded() {
		return this.isDocUploadedNeeded;
	}

	public void setIsDocUploadedNeeded(java.lang.Boolean isDocUploadedNeeded) {
		this.isDocUploadedNeeded = isDocUploadedNeeded;
	}

	public java.lang.Boolean getIsemailNeeded() {
		return this.isemailNeeded;
	}

	public void setIsemailNeeded(java.lang.Boolean isemailNeeded) {
		this.isemailNeeded = isemailNeeded;
	}

	public java.lang.String getLeadDetails() {
		return this.leadDetails;
	}

	public void setLeadDetails(java.lang.String leadDetails) {
		this.leadDetails = leadDetails;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public agreementFacilitateBO(java.lang.String agreementId,
			java.lang.String partyId, java.lang.String personId,
			java.lang.String dueDate, java.lang.String notificationDate,
			java.lang.Boolean isDocUploadedNeeded,
			java.lang.Boolean isemailNeeded, java.lang.String leadDetails,
			java.lang.Long processInstanceId) {
		this.agreementId = agreementId;
		this.partyId = partyId;
		this.personId = personId;
		this.dueDate = dueDate;
		this.notificationDate = notificationDate;
		this.isDocUploadedNeeded = isDocUploadedNeeded;
		this.isemailNeeded = isemailNeeded;
		this.leadDetails = leadDetails;
		this.processInstanceId = processInstanceId;
	}

}