package com.myspace.has;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class copyProduct implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("benefitCompletedSSD")
	private java.lang.String benefitCompletedSSD;
	@org.kie.api.definition.type.Label("benefitCompleted")
	private java.lang.String benefitCompleted;
	@org.kie.api.definition.type.Label("benefitMessage")
	private java.lang.String benefitMessage;
	@org.kie.api.definition.type.Label("copyTitle")
	private java.lang.String copyTitle;
	@org.kie.api.definition.type.Label("copyVersionFlag")
	private java.lang.Boolean copyVersionFlag;
	@org.kie.api.definition.type.Label("fromProductSpecificationId")
	private java.lang.String fromProductSpecificationId;
	@org.kie.api.definition.type.Label("processId")
	private java.lang.Long processId;
	@org.kie.api.definition.type.Label("qnaCompleted")
	private java.lang.String qnaCompleted;
	@org.kie.api.definition.type.Label("qnaCompletedSSD")
	private java.lang.String qnaCompletedSSD;
	@org.kie.api.definition.type.Label("qnaMessage")
	private java.lang.String qnaMessage;
	@org.kie.api.definition.type.Label("questionStageSequenceId")
	private java.util.List<java.lang.String> questionStageSequenceId;
	@org.kie.api.definition.type.Label("ruleSpecificationId")
	private java.util.List<java.lang.String> ruleSpecificationId;
	@org.kie.api.definition.type.Label("scriptCompleted")
	private java.lang.String scriptCompleted;
	@org.kie.api.definition.type.Label("scriptCompletedSSD")
	private java.lang.String scriptCompletedSSD;
	@org.kie.api.definition.type.Label("scriptMessage")
	private java.lang.String scriptMessage;
	@org.kie.api.definition.type.Label("staticTextBlockId")
	private java.util.List<java.lang.String> staticTextBlockId;
	@org.kie.api.definition.type.Label("task")
	private java.lang.String task;
	@org.kie.api.definition.type.Label("test")
	private java.lang.String test;
	@org.kie.api.definition.type.Label("toProductSpecificationId")
	private java.lang.String toProductSpecificationId;
	@org.kie.api.definition.type.Label("userid")
	private java.lang.String userid;
	@org.kie.api.definition.type.Label("username")
	private java.lang.String username;

	public copyProduct() {
	}

	public java.lang.String getBenefitCompletedSSD() {
		return this.benefitCompletedSSD;
	}

	public void setBenefitCompletedSSD(java.lang.String benefitCompletedSSD) {
		this.benefitCompletedSSD = benefitCompletedSSD;
	}

	public java.lang.String getBenefitCompleted() {
		return this.benefitCompleted;
	}

	public void setBenefitCompleted(java.lang.String benefitCompleted) {
		this.benefitCompleted = benefitCompleted;
	}

	public java.lang.String getBenefitMessage() {
		return this.benefitMessage;
	}

	public void setBenefitMessage(java.lang.String benefitMessage) {
		this.benefitMessage = benefitMessage;
	}

	public java.lang.String getCopyTitle() {
		return this.copyTitle;
	}

	public void setCopyTitle(java.lang.String copyTitle) {
		this.copyTitle = copyTitle;
	}

	public java.lang.Boolean getCopyVersionFlag() {
		return this.copyVersionFlag;
	}

	public void setCopyVersionFlag(java.lang.Boolean copyVersionFlag) {
		this.copyVersionFlag = copyVersionFlag;
	}

	public java.lang.String getFromProductSpecificationId() {
		return this.fromProductSpecificationId;
	}

	public void setFromProductSpecificationId(
			java.lang.String fromProductSpecificationId) {
		this.fromProductSpecificationId = fromProductSpecificationId;
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public java.lang.String getQnaCompleted() {
		return this.qnaCompleted;
	}

	public void setQnaCompleted(java.lang.String qnaCompleted) {
		this.qnaCompleted = qnaCompleted;
	}

	public java.lang.String getQnaCompletedSSD() {
		return this.qnaCompletedSSD;
	}

	public void setQnaCompletedSSD(java.lang.String qnaCompletedSSD) {
		this.qnaCompletedSSD = qnaCompletedSSD;
	}

	public java.lang.String getQnaMessage() {
		return this.qnaMessage;
	}

	public void setQnaMessage(java.lang.String qnaMessage) {
		this.qnaMessage = qnaMessage;
	}

	public java.util.List<java.lang.String> getQuestionStageSequenceId() {
		return this.questionStageSequenceId;
	}

	public void setQuestionStageSequenceId(
			java.util.List<java.lang.String> questionStageSequenceId) {
		this.questionStageSequenceId = questionStageSequenceId;
	}

	public java.util.List<java.lang.String> getRuleSpecificationId() {
		return this.ruleSpecificationId;
	}

	public void setRuleSpecificationId(
			java.util.List<java.lang.String> ruleSpecificationId) {
		this.ruleSpecificationId = ruleSpecificationId;
	}

	public java.lang.String getScriptCompleted() {
		return this.scriptCompleted;
	}

	public void setScriptCompleted(java.lang.String scriptCompleted) {
		this.scriptCompleted = scriptCompleted;
	}

	public java.lang.String getScriptCompletedSSD() {
		return this.scriptCompletedSSD;
	}

	public void setScriptCompletedSSD(java.lang.String scriptCompletedSSD) {
		this.scriptCompletedSSD = scriptCompletedSSD;
	}

	public java.lang.String getScriptMessage() {
		return this.scriptMessage;
	}

	public void setScriptMessage(java.lang.String scriptMessage) {
		this.scriptMessage = scriptMessage;
	}

	public java.util.List<java.lang.String> getStaticTextBlockId() {
		return this.staticTextBlockId;
	}

	public void setStaticTextBlockId(
			java.util.List<java.lang.String> staticTextBlockId) {
		this.staticTextBlockId = staticTextBlockId;
	}

	public java.lang.String getTask() {
		return this.task;
	}

	public void setTask(java.lang.String task) {
		this.task = task;
	}

	public java.lang.String getTest() {
		return this.test;
	}

	public void setTest(java.lang.String test) {
		this.test = test;
	}

	public java.lang.String getToProductSpecificationId() {
		return this.toProductSpecificationId;
	}

	public void setToProductSpecificationId(
			java.lang.String toProductSpecificationId) {
		this.toProductSpecificationId = toProductSpecificationId;
	}

	public java.lang.String getUserid() {
		return this.userid;
	}

	public void setUserid(java.lang.String userid) {
		this.userid = userid;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public copyProduct(java.lang.String benefitCompletedSSD,
			java.lang.String benefitCompleted, java.lang.String benefitMessage,
			java.lang.String copyTitle, java.lang.Boolean copyVersionFlag,
			java.lang.String fromProductSpecificationId,
			java.lang.Long processId, java.lang.String qnaCompleted,
			java.lang.String qnaCompletedSSD, java.lang.String qnaMessage,
			java.util.List<java.lang.String> questionStageSequenceId,
			java.util.List<java.lang.String> ruleSpecificationId,
			java.lang.String scriptCompleted,
			java.lang.String scriptCompletedSSD,
			java.lang.String scriptMessage,
			java.util.List<java.lang.String> staticTextBlockId,
			java.lang.String task, java.lang.String test,
			java.lang.String toProductSpecificationId, java.lang.String userid,
			java.lang.String username) {
		this.benefitCompletedSSD = benefitCompletedSSD;
		this.benefitCompleted = benefitCompleted;
		this.benefitMessage = benefitMessage;
		this.copyTitle = copyTitle;
		this.copyVersionFlag = copyVersionFlag;
		this.fromProductSpecificationId = fromProductSpecificationId;
		this.processId = processId;
		this.qnaCompleted = qnaCompleted;
		this.qnaCompletedSSD = qnaCompletedSSD;
		this.qnaMessage = qnaMessage;
		this.questionStageSequenceId = questionStageSequenceId;
		this.ruleSpecificationId = ruleSpecificationId;
		this.scriptCompleted = scriptCompleted;
		this.scriptCompletedSSD = scriptCompletedSSD;
		this.scriptMessage = scriptMessage;
		this.staticTextBlockId = staticTextBlockId;
		this.task = task;
		this.test = test;
		this.toProductSpecificationId = toProductSpecificationId;
		this.userid = userid;
		this.username = username;
	}

}